SELECT N, 'Root' AS NodeType
FROM BST
WHERE P IS NULL

UNION

-- Select the leaf nodes
SELECT N, 'Leaf' AS NodeType
FROM BST
WHERE N NOT IN (SELECT DISTINCT P FROM BST WHERE P IS NOT NULL) 
  AND P IS NOT NULL

UNION

-- Select the inner nodes
SELECT N, 'Inner' AS NodeType
FROM BST
WHERE P IS NOT NULL 
  AND N IN (SELECT DISTINCT P FROM BST WHERE P IS NOT NULL)

ORDER BY N;
